/// MHR Dart FK unit test
/// ======================
/// Verifies that the Dart reimplementation of the MHR forward kinematics
/// (param_transform → FK tree → LBS) produces vertices that match the
/// pymomentum ground-truth fixture to within 0.05 cm (0.5 mm).
///
/// Fixture files (generated by gen_mhr_fixture.py):
///   test/fixtures/mhr/model_params.bin   – float32[204] input
///   test/fixtures/mhr/expected_verts.bin – float32[n_verts*3] expected output (cm, Y-UP)
///   test/fixtures/mhr/fixture_manifest.json
///
/// Run with:
///   cd app/mobile
///   dart test test/mhr_model_test.dart
///
/// This test uses dart:io to read binary files directly — no Flutter framework
/// or rootBundle needed.  The MHR asset files are read from their actual paths
/// under assets/mhr/ relative to the project root.

// @dart=3.2

import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:convert';

import 'package:test/test.dart';

// ---------------------------------------------------------------------------
// Paths  (relative to project root, i.e. app/mobile/)
// ---------------------------------------------------------------------------
const String _assetDir   = 'assets/mhr';
const String _fixtureDir = 'test/fixtures/mhr';

// ---------------------------------------------------------------------------
// Standalone MHR FK engine (no Flutter, no rootBundle)
// Mirrors MhrModel exactly but reads from dart:io File instead of rootBundle.
// ---------------------------------------------------------------------------

class _MhrFk {
  // constants
  static const int _nJointsConst    = 127;
  static const int _jpRows          = 889;   // nJoints * 7
  static const int _tCols           = 321;
  static const int _modelParamsCols = 204;
  static const int _skinInfluences  = 8;

  late final Float32List _T;
  late final int _nJoints;
  late final Int16List _parents;
  late final Float32List _offsets;
  late final Float32List _preRots;
  late final Float32List _ibp;
  late final Int16List _skinIdx;
  late final Float32List _skinWgt;
  late final Float32List _restVerts;
  late final int _nVerts;

  // ── Load ──────────────────────────────────────────────────────────────────

  void load(String assetDir) {
    _parseParamTransform(_readBytes('$assetDir/param_transform.bin'));
    _parseSkeleton(_readBytes('$assetDir/skeleton.bin'));
    _parseInvBindPose(_readBytes('$assetDir/inv_bind_pose.bin'));
    _parseSkinIdx(_readBytes('$assetDir/skin_idx.bin'));
    _parseSkinWgt(_readBytes('$assetDir/skin_wgt.bin'));
    _parseRestVerts(_readBytes('$assetDir/rest_verts.bin'));
  }

  static ByteData _readBytes(String path) {
    final bytes = File(path).readAsBytesSync();
    return ByteData.sublistView(Uint8List.fromList(bytes));
  }

  // ── Parsers (exact copy from MhrModel) ────────────────────────────────────

  void _parseParamTransform(ByteData data) {
    final n = _jpRows * _tCols;
    _T = Float32List(n);
    for (int i = 0; i < n; i++) {
      _T[i] = data.getFloat32(i * 4, Endian.little);
    }
  }

  void _parseSkeleton(ByteData data) {
    int off = 0;
    _nJoints = data.getInt32(off, Endian.little); off += 4;

    _parents = Int16List(_nJoints);
    for (int j = 0; j < _nJoints; j++) {
      _parents[j] = data.getInt16(off, Endian.little); off += 2;
    }
    final pad = (4 - ((_nJoints * 2) % 4)) % 4;
    off += pad;

    _offsets = Float32List(_nJoints * 3);
    for (int i = 0; i < _nJoints * 3; i++) {
      _offsets[i] = data.getFloat32(off, Endian.little); off += 4;
    }

    _preRots = Float32List(_nJoints * 4);
    for (int i = 0; i < _nJoints * 4; i++) {
      _preRots[i] = data.getFloat32(off, Endian.little); off += 4;
    }
  }

  void _parseInvBindPose(ByteData data) {
    final n = _nJointsConst * 16;
    _ibp = Float32List(n);
    for (int i = 0; i < n; i++) {
      _ibp[i] = data.getFloat32(i * 4, Endian.little);
    }
  }

  void _parseSkinIdx(ByteData data) {
    final n = data.lengthInBytes ~/ 2;
    _skinIdx = Int16List(n);
    for (int i = 0; i < n; i++) {
      _skinIdx[i] = data.getInt16(i * 2, Endian.little);
    }
    _nVerts = n ~/ _skinInfluences;
  }

  void _parseSkinWgt(ByteData data) {
    final n = _nVerts * _skinInfluences;
    _skinWgt = Float32List(n);
    for (int i = 0; i < n; i++) {
      _skinWgt[i] = data.getFloat32(i * 4, Endian.little);
    }
  }

  void _parseRestVerts(ByteData data) {
    final n = _nVerts * 3;
    _restVerts = Float32List(n);
    for (int i = 0; i < n; i++) {
      _restVerts[i] = data.getFloat32(i * 4, Endian.little);
    }
  }

  // ── Forward pass (exact copy from MhrModel) ────────────────────────────────

  /// Returns vertices in cm (before the * 0.01 applied in MhrModel.forward()).
  Float32List forward(Float32List modelParams) {
    final jp        = _paramTransform(modelParams);
    final skelState = _fk(jp);
    final skinMats  = _buildSkinMats(skelState);
    return _lbs(skinMats);
  }

  Float32List _paramTransform(Float32List mp) {
    final jp = Float32List(_jpRows);
    for (int r = 0; r < _jpRows; r++) {
      double acc = 0.0;
      final rowBase = r * _tCols;
      for (int c = 0; c < _modelParamsCols; c++) {
        acc += _T[rowBase + c] * mp[c];
      }
      jp[r] = acc;
    }
    return jp;
  }

  Float64List _fk(Float32List jp) {
    final out = Float64List(_nJointsConst * 8);
    final gT  = Float64List(_nJointsConst * 3);
    final gQ  = Float64List(_nJointsConst * 4);
    final gS  = Float64List(_nJointsConst);

    for (int j = 0; j < _nJointsConst; j++) {
      final jpBase  = j * 7;
      final localTx = jp[jpBase];
      final localTy = jp[jpBase + 1];
      final localTz = jp[jpBase + 2];
      final rx      = jp[jpBase + 3];
      final ry      = jp[jpBase + 4];
      final rz      = jp[jpBase + 5];
      final scale   = math.exp(0.6931471824645996 * jp[jpBase + 6]);

      final localQ = _eulerZyxToQuat(rx, ry, rz);

      final preQx = _preRots[j * 4];
      final preQy = _preRots[j * 4 + 1];
      final preQz = _preRots[j * 4 + 2];
      final preQw = _preRots[j * 4 + 3];

      final cq = _quatMul(preQx, preQy, preQz, preQw,
                          localQ[0], localQ[1], localQ[2], localQ[3]);

      final offX = _offsets[j * 3];
      final offY = _offsets[j * 3 + 1];
      final offZ = _offsets[j * 3 + 2];

      final lx = offX + localTx;
      final ly = offY + localTy;
      final lz = offZ + localTz;

      final parent = _parents[j];
      double gx, gy, gz, gqx, gqy, gqz, gqw;

      if (parent < 0) {
        gx = lx; gy = ly; gz = lz;
        gqx = cq[0]; gqy = cq[1]; gqz = cq[2]; gqw = cq[3];
        gS[j] = scale;
      } else {
        final pqx = gQ[parent * 4];
        final pqy = gQ[parent * 4 + 1];
        final pqz = gQ[parent * 4 + 2];
        final pqw = gQ[parent * 4 + 3];

        final rotated = _quatRotVec(pqx, pqy, pqz, pqw, lx, ly, lz);
        final ps = gS[parent];
        gx = gT[parent * 3]     + ps * rotated[0];
        gy = gT[parent * 3 + 1] + ps * rotated[1];
        gz = gT[parent * 3 + 2] + ps * rotated[2];

        final gq = _quatMul(pqx, pqy, pqz, pqw, cq[0], cq[1], cq[2], cq[3]);
        gqx = gq[0]; gqy = gq[1]; gqz = gq[2]; gqw = gq[3];
        gS[j] = ps * scale;
      }

      gT[j * 3]     = gx;
      gT[j * 3 + 1] = gy;
      gT[j * 3 + 2] = gz;
      gQ[j * 4]     = gqx;
      gQ[j * 4 + 1] = gqy;
      gQ[j * 4 + 2] = gqz;
      gQ[j * 4 + 3] = gqw;

      final ob = j * 8;
      out[ob]     = gx;
      out[ob + 1] = gy;
      out[ob + 2] = gz;
      out[ob + 3] = gqx;
      out[ob + 4] = gqy;
      out[ob + 5] = gqz;
      out[ob + 6] = gqw;
      out[ob + 7] = gS[j];
    }
    return out;
  }

  Float32List _buildSkinMats(Float64List skelState) {
    final mats = Float32List(_nJointsConst * 16);
    for (int j = 0; j < _nJointsConst; j++) {
      final sb    = j * 8;
      final tx    = skelState[sb], ty = skelState[sb + 1], tz = skelState[sb + 2];
      final qx    = skelState[sb + 3], qy = skelState[sb + 4];
      final qz    = skelState[sb + 5], qw = skelState[sb + 6];
      final scale = skelState[sb + 7];

      final x2 = qx + qx, y2 = qy + qy, z2 = qz + qz;
      final xx = qx * x2, xy = qx * y2, xz = qx * z2;
      final yy = qy * y2, yz = qy * z2, zz = qz * z2;
      final wx = qw * x2, wy = qw * y2, wz = qw * z2;

      final g = Float32List(16);
      g[0]  = (1.0 - (yy + zz)) * scale;
      g[1]  = (xy - wz) * scale;
      g[2]  = (xz + wy) * scale;
      g[3]  = tx;
      g[4]  = (xy + wz) * scale;
      g[5]  = (1.0 - (xx + zz)) * scale;
      g[6]  = (yz - wx) * scale;
      g[7]  = ty;
      g[8]  = (xz - wy) * scale;
      g[9]  = (yz + wx) * scale;
      g[10] = (1.0 - (xx + yy)) * scale;
      g[11] = tz;
      g[12] = 0.0; g[13] = 0.0; g[14] = 0.0; g[15] = 1.0;

      final ibpBase = j * 16;
      final mBase   = j * 16;
      for (int row = 0; row < 4; row++) {
        for (int col = 0; col < 4; col++) {
          double sum = 0.0;
          for (int k = 0; k < 4; k++) {
            sum += g[row * 4 + k] * _ibp[ibpBase + k * 4 + col];
          }
          mats[mBase + row * 4 + col] = sum;
        }
      }
    }
    return mats;
  }

  Float32List _lbs(Float32List skinMats) {
    final verts = Float32List(_nVerts * 3);
    for (int v = 0; v < _nVerts; v++) {
      final rx = _restVerts[v * 3];
      final ry = _restVerts[v * 3 + 1];
      final rz = _restVerts[v * 3 + 2];
      double ox = 0, oy = 0, oz = 0;
      for (int k = 0; k < _skinInfluences; k++) {
        final w = _skinWgt[v * _skinInfluences + k];
        if (w == 0.0) continue;
        final j  = _skinIdx[v * _skinInfluences + k];
        final mb = j * 16;
        final m  = skinMats;
        ox += w * (m[mb]      * rx + m[mb + 1]  * ry + m[mb + 2]  * rz + m[mb + 3]);
        oy += w * (m[mb + 4]  * rx + m[mb + 5]  * ry + m[mb + 6]  * rz + m[mb + 7]);
        oz += w * (m[mb + 8]  * rx + m[mb + 9]  * ry + m[mb + 10] * rz + m[mb + 11]);
      }
      verts[v * 3]     = ox;
      verts[v * 3 + 1] = oy;
      verts[v * 3 + 2] = oz;
    }
    return verts;
  }

  // ── Quaternion helpers (exact copy from MhrModel) ─────────────────────────

  static List<double> _eulerZyxToQuat(double rx, double ry, double rz) {
    final cx = math.cos(rx * 0.5), sx = math.sin(rx * 0.5);
    final cy = math.cos(ry * 0.5), sy = math.sin(ry * 0.5);
    final cz = math.cos(rz * 0.5), sz = math.sin(rz * 0.5);
    return [
      sx * cy * cz - cx * sy * sz,
      cx * sy * cz + sx * cy * sz,
      cx * cy * sz - sx * sy * cz,
      cx * cy * cz + sx * sy * sz,
    ];
  }

  static List<double> _quatMul(
      double ax, double ay, double az, double aw,
      double bx, double by, double bz, double bw) {
    return [
      aw * bx + ax * bw + ay * bz - az * by,
      aw * by - ax * bz + ay * bw + az * bx,
      aw * bz + ax * by - ay * bx + az * bw,
      aw * bw - ax * bx - ay * by - az * bz,
    ];
  }

  static List<double> _quatRotVec(
      double qx, double qy, double qz, double qw,
      double vx, double vy, double vz) {
    final tx = 2.0 * (qy * vz - qz * vy);
    final ty = 2.0 * (qz * vx - qx * vz);
    final tz = 2.0 * (qx * vy - qy * vx);
    return [
      vx + qw * tx + qy * tz - qz * ty,
      vy + qw * ty + qz * tx - qx * tz,
      vz + qw * tz + qx * ty - qy * tx,
    ];
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

Float32List _readFloat32Bin(String path) {
  final bytes = File(path).readAsBytesSync();
  final bd = ByteData.sublistView(Uint8List.fromList(bytes));
  final n  = bytes.length ~/ 4;
  final out = Float32List(n);
  for (int i = 0; i < n; i++) {
    out[i] = bd.getFloat32(i * 4, Endian.little);
  }
  return out;
}

double _maxAbsError(Float32List a, Float32List b) {
  double maxErr = 0.0;
  for (int i = 0; i < a.length; i++) {
    final e = (a[i] - b[i]).abs();
    if (e > maxErr) maxErr = e;
  }
  return maxErr;
}

double _meanAbsError(Float32List a, Float32List b) {
  double sum = 0.0;
  for (int i = 0; i < a.length; i++) {
    sum += (a[i] - b[i]).abs();
  }
  return sum / a.length;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  late _MhrFk fk;
  late Float32List modelParams;
  late Float32List expectedVerts;
  late Map<String, dynamic> manifest;

  setUpAll(() {
    // Load manifest
    final mf = File('$_fixtureDir/fixture_manifest.json').readAsStringSync();
    manifest = json.decode(mf) as Map<String, dynamic>;

    // Load assets
    fk = _MhrFk();
    fk.load(_assetDir);

    // Load fixture inputs/outputs
    modelParams   = _readFloat32Bin('$_fixtureDir/model_params.bin');
    expectedVerts = _readFloat32Bin('$_fixtureDir/expected_verts.bin');
  });

  group('MHR Dart FK vs pymomentum', () {

    test('model_params fixture has correct length (204)', () {
      expect(modelParams.length, equals(204));
    });

    test('expected_verts fixture has correct length (n_verts * 3)', () {
      final nVerts = manifest['n_verts'] as int;
      expect(expectedVerts.length, equals(nVerts * 3));
    });

    test('Dart FK output length matches fixture', () {
      final dartVerts = fk.forward(modelParams);
      final nVerts    = manifest['n_verts'] as int;
      expect(dartVerts.length, equals(nVerts * 3));
    });

    test('Dart FK max error < threshold vs pymomentum', () {
      final dartVerts       = fk.forward(modelParams);
      final thresholdCm     = (manifest['threshold_cm'] as num).toDouble();
      final maxErr          = _maxAbsError(dartVerts, expectedVerts);
      final meanErr         = _meanAbsError(dartVerts, expectedVerts);

      print('');
      print('  Dart FK vs pymomentum:');
      print('    max  error = ${maxErr.toStringAsFixed(5)} cm');
      print('    mean error = ${meanErr.toStringAsFixed(5)} cm');
      print('    threshold  = $thresholdCm cm');

      expect(maxErr, lessThan(thresholdCm),
          reason: 'Dart FK max vertex error ${maxErr.toStringAsFixed(4)} cm '
                  'exceeds threshold $thresholdCm cm');
    });

    test('Dart FK head vertex is near top of body (Y-UP sanity check)', () {
      // The highest Y vertex should be near 169 cm (head crown).
      // If the body is upside-down, this would be near 0.
      final dartVerts = fk.forward(modelParams);
      final nVerts    = manifest['n_verts'] as int;
      double maxY = -1e9;
      for (int v = 0; v < nVerts; v++) {
        final y = dartVerts[v * 3 + 1];
        if (y > maxY) maxY = y;
      }
      print('');
      print('  Max Y vertex (should be ~169 cm for head): ${maxY.toStringAsFixed(1)} cm');
      expect(maxY, greaterThan(150.0),
          reason: 'Max Y = ${maxY.toStringAsFixed(1)} cm — body appears upside-down or not loaded');
    });

    test('cm→m scale: vertices in metres have max |Y| ≈ 1.7 m', () {
      // MhrModel.forward() multiplies by 0.01.  Verify the scale is correct.
      final dartVerts = fk.forward(modelParams);
      final nVerts    = manifest['n_verts'] as int;
      double maxY = -1e9;
      for (int v = 0; v < nVerts; v++) {
        final y = dartVerts[v * 3 + 1] * 0.01; // cm → m
        if (y > maxY) maxY = y;
      }
      print('');
      print('  Max Y in metres (should be ~1.70 m): ${maxY.toStringAsFixed(3)} m');
      expect(maxY, greaterThan(1.5),
          reason: 'Scaling to metres gives max Y ${maxY.toStringAsFixed(3)} m — wrong scale?');
      expect(maxY, lessThan(2.5),
          reason: 'Scaling to metres gives max Y ${maxY.toStringAsFixed(3)} m — too large?');
    });

  });
}
